version: 0.0
os: linux
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - directory
      - file
files:
  - source: ./
    destination: /home/ubuntu/stock_platform
hooks:
  BeforeInstall:
    - location: scripts/before_install.bash
      timeout: 300
      runas: root
  Install:
   - location: scripts/install.bash
     runas: root
  ApplicationStart:
   - location: scripts/app_start.bash
     runas: root